use std::process::Command;
use crate::config::Config;

fn home() -> String {
    std::env::var("HOME").unwrap_or_default()
}

fn darken(hex: &str, factor: f32) -> String {
    let h = hex.trim_start_matches('#');
    if h.len() < 6 { return hex.to_string(); }
    let r = u8::from_str_radix(&h[0..2], 16).unwrap_or(0);
    let g = u8::from_str_radix(&h[2..4], 16).unwrap_or(0);
    let b = u8::from_str_radix(&h[4..6], 16).unwrap_or(0);
    format!("#{:02x}{:02x}{:02x}",
        (r as f32 * factor) as u8,
        (g as f32 * factor) as u8,
        (b as f32 * factor) as u8)
}

fn hex_to_rgba(hex: &str, alpha: f32) -> String {
    let h = hex.trim_start_matches('#');
    if h.len() < 6 { return format!("rgba(128,128,128,{alpha})"); }
    let r = u8::from_str_radix(&h[0..2], 16).unwrap_or(128);
    let g = u8::from_str_radix(&h[2..4], 16).unwrap_or(128);
    let b = u8::from_str_radix(&h[4..6], 16).unwrap_or(128);
    format!("rgba({r},{g},{b},{alpha})")
}

/// Full theme apply: waybar CSS + sway client colors + layout + reload
pub fn apply_theme(config: &Config) {
    write_waybar_theme(config);
    write_wofi_theme(config);
    update_sway_client_colors(config);
    update_sway_layout(config);
    apply_wallpaper(config);
    // swaymsg reload restarts waybar via exec_always in sway config
    reload();
    // Reload only sets defaults for new workspaces/windows — push the new
    // gaps and borders onto everything that already exists.
    set_gaps_inner(config.gaps_inner);
    set_gaps_outer(config.gaps_outer);
    set_border_width(config.border_width);
    run_power_apply();
}

/// Persist gaps + border width into the sway config file.
fn update_sway_layout(config: &Config) {
    let replacements: [(&str, String); 4] = [
        ("gaps inner", format!("gaps inner {}", config.gaps_inner)),
        ("gaps outer", format!("gaps outer {}", config.gaps_outer)),
        ("default_border pixel", format!("default_border pixel {}", config.border_width)),
        ("default_floating_border pixel", format!("default_floating_border pixel {}", config.border_width)),
    ];

    let config_path = format!("{}/.config/sway/config", home());
    let content = match std::fs::read_to_string(&config_path) {
        Ok(c) => c,
        Err(_) => return,
    };

    let mut lines: Vec<String> = content.lines().map(|l| l.to_string()).collect();
    let mut handled = [false; 4];

    for line in &mut lines {
        let trimmed = line.trim_start().to_string();
        for (i, (key, new_line)) in replacements.iter().enumerate() {
            if trimmed.starts_with(key) && !handled[i] {
                *line = new_line.clone();
                handled[i] = true;
            }
        }
    }
    for (i, (_, new_line)) in replacements.iter().enumerate() {
        if !handled[i] {
            lines.push(new_line.clone());
        }
    }

    let _ = std::fs::write(&config_path, lines.join("\n") + "\n");
}

fn write_waybar_theme(config: &Config) {
    let bar_bg  = &config.bar_bg;
    let text    = &config.bar_text;
    let accent  = &config.accent;
    let urgent  = &config.urgent_color;
    let inactive = &config.inactive_color;
    let sec_bg  = &config.sec_bg;

    let css = format!(
r#"/* Auto-generated by settings-manager — do not edit */
window#waybar,
window#waybar > box,
window#waybar > box > box {{
  background-color: {bar_bg};
  color: {text};
}}
#cpu, #memory, #pulseaudio, #clock {{
  background-color: {sec_bg};
  border: 1px solid {inactive};
}}
#workspaces button.focused {{
  color: {accent};
  border-top: 1px solid {accent};
  border-bottom: 1px solid {accent};
  border-left: 3px solid {accent};
  border-right: 3px solid {accent};
}}
#workspaces button:hover {{
  color: {inactive};
  background-color: rgba(255,255,255,0.05);
}}
#bluetooth.on,
#bluetooth.discoverable,
#bluetooth.pairable {{
  color: {accent};
}}
#bluetooth.connected {{
  color: {accent};
  border-left: 2px solid {accent};
}}
#network.wifi,
#network.ethernet {{
  color: {accent};
}}
#cpu.warning, #memory.warning {{
  color: {accent};
  border-color: {accent};
}}
#cpu.critical, #memory.critical {{
  color: {urgent};
  border-color: {urgent};
}}
"#);

    let overrides_path = format!("{}/.config/waybar/theme-overrides.css", home());
    let _ = std::fs::write(&overrides_path, css);

    // One-time: prepend @import to style.css if not already there
    let style_path = format!("{}/.config/waybar/style.css", home());
    if let Ok(content) = std::fs::read_to_string(&style_path) {
        if !content.contains("theme-overrides.css") {
            let patched = format!("@import \"theme-overrides.css\";\n\n{}", content);
            let _ = std::fs::write(&style_path, patched);
        }
    }
}

/// wofi (used for app search, clipboard history, and notification history)
/// otherwise renders with the bare default GTK theme — jarring against
/// everything else here. wofi auto-loads `style.css` from its own config
/// dir with no extra wiring needed, same way waybar's does.
fn write_wofi_theme(config: &Config) {
    let bar_bg = &config.bar_bg;
    let sec_bg = &config.sec_bg;
    let text = &config.bar_text;
    let accent = &config.accent;
    let border = hex_to_rgba(&config.bar_text, 0.22);
    let selection_bg = hex_to_rgba(&config.accent, 0.25);
    let radius = config.corner_radius.max(4.0);

    let css = format!(
r#"/* Auto-generated by settings-manager — do not edit */
window#window {{
  background-color: {bar_bg};
  border: 1px solid {border};
  border-radius: {radius}px;
}}
#input {{
  background-color: {sec_bg};
  color: {text};
  border: 1px solid {border};
  border-radius: {radius}px;
  margin: 6px;
  padding: 6px 10px;
}}
#outer-box {{
  background-color: {bar_bg};
  border-radius: {radius}px;
  margin: 4px;
}}
#scroll {{
  margin: 4px;
}}
#inner-box {{
  background-color: {bar_bg};
}}
#text {{
  color: {text};
}}
#entry {{
  padding: 6px;
  border-radius: {radius}px;
}}
#entry:selected {{
  background-color: {selection_bg};
}}
#entry:selected #text {{
  color: {accent};
}}
"#);

    let dir = format!("{}/.config/wofi", home());
    let _ = std::fs::create_dir_all(&dir);
    let _ = std::fs::write(format!("{dir}/style.css"), css);
}

fn update_sway_client_colors(config: &Config) {
    let accent   = &config.accent;
    let bar_bg   = &config.bar_bg;
    let bar_text = &config.bar_text;
    let sec_bg   = &config.sec_bg;
    let inactive = &config.inactive_color;
    let urgent   = &config.urgent_color;

    let dark_inactive = darken(inactive, 0.6);
    let dark_urgent   = darken(urgent, 0.4);

    // format: client.X  border  bg  text  indicator  child_border
    let replacements = [
        ("client.focused",
         format!("client.focused          {} {} {} {} {}", accent, sec_bg, bar_text, accent, accent)),
        ("client.focused_inactive",
         format!("client.focused_inactive {} {} {} {} {}", inactive, bar_bg, bar_text, inactive, inactive)),
        ("client.unfocused",
         format!("client.unfocused        {} {} {} {} {}", dark_inactive, bar_bg, bar_text, bar_bg, dark_inactive)),
        ("client.urgent",
         format!("client.urgent           {} {} {} {} {}", urgent, dark_urgent, bar_text, urgent, urgent)),
    ];

    let config_path = format!("{}/.config/sway/config", home());
    let content = match std::fs::read_to_string(&config_path) {
        Ok(c) => c,
        Err(_) => return,
    };

    let mut lines: Vec<String> = content.lines().map(|l| l.to_string()).collect();
    let mut handled = [false; 4];

    for line in &mut lines {
        let trimmed = line.trim_start().to_string();
        for (i, (key, new_line)) in replacements.iter().enumerate() {
            if trimmed.starts_with(key) {
                *line = new_line.clone();
                handled[i] = true;
            }
        }
    }
    // Append any that weren't found
    for (i, (_, new_line)) in replacements.iter().enumerate() {
        if !handled[i] {
            lines.push(new_line.clone());
        }
    }

    let _ = std::fs::write(&config_path, lines.join("\n") + "\n");
}

fn is_vertical(pos: &str) -> bool {
    pos == "left" || pos == "right"
}

/// Patch waybar's own config file for a new screen edge, thickness, or
/// clock setup — position and layer-orientation both change: bar thickness
/// (width vs height) and every module format that stacks its label
/// vertically on a `left`/`right` bar need to become single-line when the
/// bar goes `top`/`bottom`, and back again when it returns to a vertical
/// edge. SIGUSR2 reload can't apply any of this, so this kills and
/// relaunches the process instead.
pub fn set_waybar_layout(config: &Config) {
    let pos = config.waybar_position.as_str();
    let thickness = config.waybar_thickness;

    let config_path = format!("{}/.config/waybar/config", home());
    let Ok(content) = std::fs::read_to_string(&config_path) else { return };
    let Ok(mut root): Result<serde_json::Value, _> = serde_json::from_str(&content) else { return };
    let Some(map) = root.as_object_mut() else { return };

    map.insert("position".into(), serde_json::Value::String(pos.to_string()));

    if is_vertical(pos) {
        map.remove("height");
        map.insert("width".into(), serde_json::json!(thickness));
    } else {
        map.remove("width");
        map.insert("height".into(), serde_json::json!(thickness));
    }

    let vertical = is_vertical(pos);

    if let Some(ws) = map.get_mut("sway/workspaces").and_then(|v| v.as_object_mut()) {
        ws.insert("format".into(), serde_json::json!(if vertical {
            "<span size='xx-large'>{name}</span>\n<span size='x-small'>─────</span>\n{windows}"
        } else {
            "<span size='large'>{name}</span> <span size='x-small'>│</span> {windows}"
        }));
        ws.insert("format-window-separator".into(), serde_json::json!(if vertical { "\n" } else { " " }));
        if let Some(rewrite) = ws.get_mut("window-rewrite").and_then(|v| v.as_object_mut()) {
            for v in rewrite.values_mut() {
                if let Some(s) = v.as_str() {
                    let swapped = if vertical {
                        s.replace("size='large'", "size='xx-large'")
                    } else {
                        s.replace("size='xx-large'", "size='large'")
                    };
                    *v = serde_json::Value::String(swapped);
                }
            }
        }
    }

    // On a vertical bar, "10:30 PM" on one line is wider than the column —
    // wrap AM/PM to its own line instead of widening the whole bar. On a
    // horizontal bar there's no such constraint, so it stays inline there.
    let vertical_time_part = if config.clock_12h { "%I:%M\n%p" } else { "%H:%M" };
    let horizontal_time_part = if config.clock_12h { "%I:%M %p" } else { "%H:%M" };
    let clock_format: String = if vertical {
        format!("{{:%Z\n%m|%d\n{vertical_time_part}}}")
    } else {
        format!("{{:%Z %m/%d {horizontal_time_part}}}")
    };
    let clock_tooltip: String = if config.clock_12h {
        "{:%Y-%m-%d %I:%M:%S %p}".to_string()
    } else {
        "{:%Y-%m-%d %H:%M:%S}".to_string()
    };

    if let Some(clock) = map.get_mut("clock").and_then(|v| v.as_object_mut()) {
        clock.insert("format".into(), serde_json::json!(clock_format));
        clock.insert("tooltip-format".into(), serde_json::json!(clock_tooltip));
        if config.clock_timezone.is_empty() {
            clock.remove("timezone");
        } else {
            clock.insert("timezone".into(), serde_json::json!(config.clock_timezone));
        }
    }

    // Drop any previously-generated extra clock widgets, then re-add one per
    // configured clock — keeps repeated edits idempotent instead of piling
    // up stale `clock#N` blocks. Placement in the module lists is owned by
    // config.modules_left/center/right (see below), not generated here.
    let stale_ids: Vec<String> = map.keys()
        .filter(|k| k.starts_with("clock#"))
        .cloned()
        .collect();
    for id in &stale_ids {
        map.remove(id);
    }
    for cc in &config.extra_clocks {
        map.insert(cc.module_id(), serde_json::json!({
            "format": clock_format,
            "tooltip-format": clock_tooltip,
            "timezone": cc.timezone,
        }));
    }

    // Module arrangement (drag-arrange screen) is the single source of
    // truth once seeded; an empty list here means "never seeded / user
    // hasn't touched it", so leave whatever's already in the bar file alone
    // rather than blanking a section out.
    for (section, modules) in [
        ("modules-left", &config.modules_left),
        ("modules-center", &config.modules_center),
        ("modules-right", &config.modules_right),
    ] {
        if !modules.is_empty() {
            map.insert(section.into(), serde_json::json!(modules));
        }
    }

    if let Some(cpu) = map.get_mut("cpu").and_then(|v| v.as_object_mut()) {
        cpu.insert("format".into(), serde_json::json!(if vertical { "CPU\n{usage}%" } else { "CPU {usage}%" }));
    }

    if let Some(mem) = map.get_mut("memory").and_then(|v| v.as_object_mut()) {
        mem.insert("format".into(), serde_json::json!(if vertical { "RAM\n{percentage}%" } else { "RAM {percentage}%" }));
    }

    if let Some(net) = map.get_mut("network").and_then(|v| v.as_object_mut()) {
        net.insert("format-wifi".into(), serde_json::json!(if vertical { "󰖩\n{essid}" } else { "󰖩 {essid}" }));
    }

    if let Some(pulse) = map.get_mut("pulseaudio").and_then(|v| v.as_object_mut()) {
        pulse.insert("format".into(), serde_json::json!(if vertical { "󰕾\n{volume}%" } else { "󰕾 {volume}%" }));
        pulse.insert("format-muted".into(), serde_json::json!(if vertical { "󰖁\nMUTE" } else { "󰖁 MUTE" }));
    }

    let Ok(pretty) = serde_json::to_string_pretty(&root) else { return };
    let _ = std::fs::write(&config_path, pretty + "\n");

    set_clock_css_padding(vertical);
    set_module_thickness_css(thickness);

    let _ = Command::new("pkill").arg("waybar").output();
    let _ = Command::new("waybar").spawn();
}

/// Every module's `min-width`/`min-height: Npx;` in style.css hardcodes the
/// module's cross-axis size — CSS min-size wins over whatever `width`/
/// `height` we write into waybar's own JSON config, so without this the
/// thickness setting silently does nothing once it's below the hardcoded
/// value (and can't grow past it either). Value-agnostic: matches any
/// current `Npx` so repeated thickness changes stay idempotent, and
/// deliberately excludes the `* { min-height: 0; }` reset since that value
/// has no `px` suffix.
fn set_module_thickness_css(thickness: i32) {
    let style_path = format!("{}/.config/waybar/style.css", home());
    let Ok(content) = std::fs::read_to_string(&style_path) else { return };

    let lines: Vec<String> = content.lines().map(|l| {
        let trimmed = l.trim();
        let prop = if trimmed.starts_with("min-width:") {
            Some("min-width")
        } else if trimmed.starts_with("min-height:") {
            Some("min-height")
        } else {
            None
        };
        if let Some(prop) = prop {
            if trimmed.ends_with("px;") {
                let indent = &l[..l.len() - l.trim_start().len()];
                return format!("{indent}{prop}: {thickness}px;");
            }
        }
        l.to_string()
    }).collect();

    let _ = std::fs::write(&style_path, lines.join("\n") + "\n");
}

/// The clock's vertical layout (`left`/`right` bar) needs top-only padding
/// since the format string is already 3 lines tall; the horizontal layout
/// (`top`/`bottom` bar) is single-line and was sitting flush against its
/// own border on the left/right, so it needs side padding instead.
fn set_clock_css_padding(vertical: bool) {
    let style_path = format!("{}/.config/waybar/style.css", home());
    let Ok(content) = std::fs::read_to_string(&style_path) else { return };

    let new_padding = if vertical { "4px 0px 0px 0px" } else { "4px 10px" };
    let mut in_clock = false;
    let mut patched = false;
    let lines: Vec<String> = content.lines().map(|l| {
        let trimmed = l.trim();
        if trimmed == "#clock {" {
            in_clock = true;
        } else if in_clock && trimmed == "}" {
            in_clock = false;
        } else if in_clock && trimmed.starts_with("padding:") {
            patched = true;
            let indent = &l[..l.len() - l.trim_start().len()];
            return format!("{indent}padding: {new_padding};");
        }
        l.to_string()
    }).collect();

    if !patched {
        return;
    }
    let _ = std::fs::write(&style_path, lines.join("\n") + "\n");
}

pub fn reload() {
    let _ = Command::new("swaymsg").arg("reload").output();
}

pub fn set_gaps_inner(px: i32) {
    let _ = Command::new("swaymsg")
        .args(["gaps", "inner", "all", "set", &px.to_string()])
        .output();
}

pub fn set_gaps_outer(px: i32) {
    let _ = Command::new("swaymsg")
        .args(["gaps", "outer", "all", "set", &px.to_string()])
        .output();
}

pub fn set_border_width(px: i32) {
    let _ = Command::new("swaymsg")
        .args(["default_border", "pixel", &px.to_string()])
        .output();
    let _ = Command::new("swaymsg")
        .args(["default_floating_border", "pixel", &px.to_string()])
        .output();
    // Defaults only affect new windows — restyle existing ones too
    // (app_id matches wayland windows, class matches xwayland).
    let _ = Command::new("swaymsg")
        .arg(format!("[app_id=\".*\"] border pixel {px}"))
        .output();
    let _ = Command::new("swaymsg")
        .arg(format!("[class=\".*\"] border pixel {px}"))
        .output();
}

pub fn run_power_apply() {
    let _ = Command::new("sway-power-apply").output();
}

pub fn get_outputs() -> Vec<String> {
    let out = Command::new("swaymsg")
        .args(["-t", "get_outputs"])
        .output()
        .ok();
    out.and_then(|o| {
        let s = String::from_utf8_lossy(&o.stdout).to_string();
        let v: serde_json::Value = serde_json::from_str(&s).ok()?;
        Some(
            v.as_array()?
                .iter()
                .filter_map(|o| o["name"].as_str().map(|s| s.to_string()))
                .collect(),
        )
    })
    .unwrap_or_default()
}

#[derive(Debug, Clone)]
pub struct MonitorInfo {
    pub name: String,
    pub make: String,
    pub model: String,
    pub x: i32,
    pub y: i32,
    pub width: i32,
    pub height: i32,
    pub current_mode: String,
    pub modes: Vec<String>,
    pub active: bool,
}

pub fn get_monitor_info() -> Vec<MonitorInfo> {
    let output = match Command::new("swaymsg").args(["-t", "get_outputs"]).output() {
        Ok(o) => o,
        Err(_) => return Vec::new(),
    };
    let json_str = String::from_utf8_lossy(&output.stdout);
    let v: serde_json::Value = match serde_json::from_str(&json_str) {
        Ok(v) => v,
        Err(_) => return Vec::new(),
    };
    let arr = match v.as_array() {
        Some(a) => a,
        None => return Vec::new(),
    };

    arr.iter().map(|o| {
        let name = o["name"].as_str().unwrap_or("").to_string();
        let make = o["make"].as_str().unwrap_or("Unknown").to_string();
        let model = o["model"].as_str().unwrap_or("Unknown").to_string();
        let x = o["rect"]["x"].as_i64().unwrap_or(0) as i32;
        let y = o["rect"]["y"].as_i64().unwrap_or(0) as i32;
        let width = o["rect"]["width"].as_i64().unwrap_or(1920) as i32;
        let height = o["rect"]["height"].as_i64().unwrap_or(1080) as i32;
        let active = o["active"].as_bool().unwrap_or(false);

        let cm = &o["current_mode"];
        let cw = cm["width"].as_i64().unwrap_or(0);
        let ch = cm["height"].as_i64().unwrap_or(0);
        let cr = cm["refresh"].as_i64().unwrap_or(0);
        let current_mode = format!("{}x{}@{}Hz", cw, ch, cr / 1000);

        let mut modes: Vec<String> = o["modes"].as_array()
            .map(|modes| {
                modes.iter().map(|m| {
                    let w = m["width"].as_i64().unwrap_or(0);
                    let h = m["height"].as_i64().unwrap_or(0);
                    let r = m["refresh"].as_i64().unwrap_or(0);
                    format!("{}x{}@{}Hz", w, h, r / 1000)
                }).collect()
            })
            .unwrap_or_default();
        modes.dedup();

        MonitorInfo { name, make, model, x, y, width, height, current_mode, modes, active }
    }).collect()
}

pub fn set_monitor_mode(output_name: &str, mode: &str) {
    let _ = Command::new("swaymsg")
        .args(["output", output_name, "mode", mode])
        .output();
}

#[derive(Debug, Clone)]
pub struct SystemdServiceInfo {
    pub unit: String,
    pub enabled: bool,
}

/// User-level systemd services that are meaningfully toggleable — i.e.
/// `systemctl --user list-unit-files` reports them as plainly `enabled` or
/// `disabled` (not `static`/`alias`/`generated`/`transient`/`indirect`,
/// which can't be flipped this way) and aren't instance templates like
/// `foo@.service`, which need an instance name to mean anything.
pub fn get_systemd_user_services() -> Vec<SystemdServiceInfo> {
    let output = match Command::new("systemctl")
        .args(["--user", "list-unit-files", "--type=service", "--no-legend"])
        .output()
    {
        Ok(o) => o,
        Err(_) => return Vec::new(),
    };
    let text = String::from_utf8_lossy(&output.stdout);
    let mut services: Vec<SystemdServiceInfo> = text.lines()
        .filter_map(|line| {
            let mut cols = line.split_whitespace();
            let unit = cols.next()?.to_string();
            let state = cols.next()?;
            if unit.contains("@.service") {
                return None;
            }
            match state {
                "enabled" => Some(SystemdServiceInfo { unit, enabled: true }),
                "disabled" => Some(SystemdServiceInfo { unit, enabled: false }),
                _ => None,
            }
        })
        .collect();
    services.sort_by(|a, b| a.unit.cmp(&b.unit));
    services
}

pub fn set_systemd_service_enabled(unit: &str, enabled: bool) {
    let action = if enabled { "enable" } else { "disable" };
    let _ = Command::new("systemctl")
        .args(["--user", action, unit])
        .output();
}

/// System-level (not `--user`) services — things like tailscaled,
/// NetworkManager, etc. that run as root and aren't visible to the
/// per-session `--user` service manager at all.
pub fn get_system_services() -> Vec<SystemdServiceInfo> {
    let output = match Command::new("systemctl")
        .args(["list-unit-files", "--type=service", "--no-legend"])
        .output()
    {
        Ok(o) => o,
        Err(_) => return Vec::new(),
    };
    let text = String::from_utf8_lossy(&output.stdout);
    let mut services: Vec<SystemdServiceInfo> = text.lines()
        .filter_map(|line| {
            let mut cols = line.split_whitespace();
            let unit = cols.next()?.to_string();
            let state = cols.next()?;
            if unit.contains("@.service") {
                return None;
            }
            match state {
                "enabled" => Some(SystemdServiceInfo { unit, enabled: true }),
                "disabled" => Some(SystemdServiceInfo { unit, enabled: false }),
                _ => None,
            }
        })
        .collect();
    services.sort_by(|a, b| a.unit.cmp(&b.unit));
    services
}

/// No polkit graphical auth agent is running in this sway session, so
/// `pkexec` can't show a password prompt — instead this spawns the user's
/// terminal running `sudo systemctl enable/disable`, which prompts for the
/// password right there. The GUI can't know if that succeeds (it's an
/// interactive, detached process), so the toggle reflects optimistically
/// until the Power tab is next reopened, which re-reads real state.
pub fn set_system_service_enabled(terminal: &str, unit: &str, enabled: bool) {
    let action = if enabled { "enable" } else { "disable" };
    let script = format!(
        "sudo systemctl {action} {unit}; echo; read -rsn1 -p 'Press any key to close...'"
    );
    let term = if terminal.is_empty() { "alacritty" } else { terminal };
    let _ = Command::new(term)
        .arg("-e")
        .arg("bash")
        .arg("-c")
        .arg(script)
        .spawn();
}

#[derive(Debug, Clone)]
pub struct StartupExecEntry {
    pub line_index: usize,
    pub original_line: String,
    pub always: bool,
    pub command: String,
    pub enabled: bool,
}

fn strip_leading_hash(line: &str) -> String {
    let trimmed = line.trim_start();
    let indent = &line[..line.len() - trimmed.len()];
    format!("{}{}", indent, trimmed.trim_start_matches('#').trim_start())
}

fn add_leading_hash(line: &str) -> String {
    let trimmed = line.trim_start();
    let indent = &line[..line.len() - trimmed.len()];
    format!("{indent}# {trimmed}")
}

/// Single-line `exec`/`exec_always` startup commands from the sway config —
/// the toggleable subset of sway's own autostart list. Deliberately skips:
/// brace-block form (`exec_always { ... }`), line-continuations (trailing
/// `\`), and anything inside a nested block — those aren't safe to comment
/// out one line at a time without breaking the surrounding statement.
pub fn get_startup_execs() -> Vec<StartupExecEntry> {
    let config_path = format!("{}/.config/sway/config", home());
    let Ok(content) = std::fs::read_to_string(&config_path) else { return Vec::new() };

    let mut out = Vec::new();
    let mut depth: i32 = 0;
    for (idx, line) in content.lines().enumerate() {
        let trimmed = line.trim();
        let (is_disabled, working) = match trimmed.strip_prefix('#') {
            Some(rest) => (true, rest.trim_start()),
            None => (false, trimmed),
        };

        if is_disabled {
            // A plain comment must not affect brace depth; only continue
            // parsing it as a possible disabled exec line below.
        } else if trimmed.starts_with('}') {
            depth -= 1;
        }

        if depth == 0 && !trimmed.ends_with('\\') && !working.ends_with('{') {
            let (always, rest) = if let Some(r) = working.strip_prefix("exec_always ") {
                (true, r)
            } else if let Some(r) = working.strip_prefix("exec ") {
                (false, r)
            } else {
                (false, "")
            };
            let command = rest.trim();
            if !command.is_empty() {
                out.push(StartupExecEntry {
                    line_index: idx,
                    original_line: line.to_string(),
                    always,
                    command: command.to_string(),
                    enabled: !is_disabled,
                });
            }
        }

        if !is_disabled {
            if trimmed.ends_with('{') {
                depth += 1;
            }
        }
    }
    out
}

/// Comments or uncomments one specific line by index, verifying it still
/// matches `expected` first (defensive against the file having changed
/// since the list was loaded) — returns the new line text on success.
pub fn toggle_startup_exec(line_index: usize, expected: &str, enable: bool) -> Option<String> {
    let config_path = format!("{}/.config/sway/config", home());
    let content = std::fs::read_to_string(&config_path).ok()?;
    let mut lines: Vec<String> = content.lines().map(str::to_string).collect();

    if lines.get(line_index).map(String::as_str) != Some(expected) {
        return None;
    }
    let new_line = if enable { strip_leading_hash(expected) } else { add_leading_hash(expected) };
    lines[line_index] = new_line.clone();
    std::fs::write(&config_path, lines.join("\n") + "\n").ok()?;
    reload();
    Some(new_line)
}

/// Every cursor theme installed with a `cursors/` subdirectory, from both
/// system and user icon directories.
pub fn get_available_cursor_themes() -> Vec<String> {
    let mut dirs = vec!["/usr/share/icons".to_string()];
    dirs.push(format!("{}/.local/share/icons", home()));
    dirs.push(format!("{}/.icons", home()));

    let mut themes = std::collections::BTreeSet::new();
    for dir in dirs {
        let Ok(entries) = std::fs::read_dir(&dir) else { continue };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.join("cursors").is_dir() {
                if let Some(name) = path.file_name().and_then(|n| n.to_str()) {
                    themes.insert(name.to_string());
                }
            }
        }
    }
    themes.into_iter().collect()
}

/// Replaces the first top-level line starting with `prefix`, or appends
/// `new_line` near the top (right after the `### Variables` marker sway's
/// default config ships with, falling back to the very start of the file)
/// if no such line exists yet.
fn upsert_sway_config_line(prefix: &str, new_line: &str) {
    let config_path = format!("{}/.config/sway/config", home());
    let Ok(content) = std::fs::read_to_string(&config_path) else { return };
    let mut lines: Vec<String> = content.lines().map(str::to_string).collect();

    if let Some(pos) = lines.iter().position(|l| l.trim().starts_with(prefix)) {
        lines[pos] = new_line.to_string();
    } else {
        let insert_at = lines.iter().position(|l| l.trim() == "### Variables").unwrap_or(0);
        lines.insert(insert_at, new_line.to_string());
    }
    let _ = std::fs::write(&config_path, lines.join("\n") + "\n");
}

pub fn set_mouse_sensitivity(accel: f32) {
    let value = format!("{accel:.2}");
    let _ = Command::new("swaymsg")
        .args(["input", "type:pointer", "pointer_accel", &value])
        .output();
    upsert_sway_config_line("input type:pointer pointer_accel", &format!("input type:pointer pointer_accel {value}"));
}

pub fn set_cursor(theme: &str, size: i32) {
    let _ = Command::new("swaymsg")
        .args(["seat", "seat0", "xcursor_theme", theme, &size.to_string()])
        .output();
    upsert_sway_config_line("seat seat0 xcursor_theme", &format!("seat seat0 xcursor_theme {theme} {size}"));
}

// ── Network / Bluetooth ─────────────────────────────────────────────────────
//
// This machine runs systemd-networkd + iwd (no NetworkManager, no nmcli),
// so wifi is driven through `iwctl` and ethernet through `ip`. `iwctl`
// always emits ANSI color codes even when piped, so its output gets
// stripped before parsing.

fn strip_ansi(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut chars = s.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' && chars.peek() == Some(&'[') {
            chars.next();
            for c2 in chars.by_ref() {
                if c2.is_ascii_alphabetic() {
                    break;
                }
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Splits an already-ANSI-stripped table row on runs of 2+ spaces — iwctl's
/// column padding — while keeping single spaces inside a field (network
/// names like "Narnea Home" or "[oven] Samsung"). A run of exactly one
/// space is only ever a real inter-word space here, never a boundary.
fn split_table_columns(line: &str) -> Vec<String> {
    let mut cols = Vec::new();
    let mut current = String::new();
    let mut pending_spaces = 0u32;
    for c in line.chars() {
        if c == ' ' {
            pending_spaces += 1;
        } else {
            if pending_spaces >= 2 {
                let trimmed = current.trim();
                if !trimmed.is_empty() {
                    cols.push(trimmed.to_string());
                }
                current.clear();
            } else if pending_spaces == 1 && !current.is_empty() {
                current.push(' ');
            }
            pending_spaces = 0;
            current.push(c);
        }
    }
    let trimmed = current.trim();
    if !trimmed.is_empty() {
        cols.push(trimmed.to_string());
    }
    cols
}

/// Same column-boundary logic as `split_table_columns`, but for text that
/// still has its ANSI escape codes — iwctl represents each network's
/// signal strength as always-4 literal `*` characters, using color (dim
/// gray for the "off" bars) to show actual strength rather than the
/// character count. Escape sequences are kept verbatim inside whichever
/// column they fall in (invisible for column-boundary purposes) so
/// `count_active_stars` can later tell dim stars from bright ones.
fn split_table_columns_raw(line: &str) -> Vec<String> {
    let mut cols = Vec::new();
    let mut current = String::new();
    let mut pending_spaces = 0u32;
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' && chars.peek() == Some(&'[') {
            current.push(c);
            current.push(chars.next().unwrap());
            for c2 in chars.by_ref() {
                current.push(c2);
                if c2.is_ascii_alphabetic() {
                    break;
                }
            }
            continue;
        }
        if c == ' ' {
            pending_spaces += 1;
        } else {
            if pending_spaces >= 2 {
                if !strip_ansi(&current).trim().is_empty() {
                    cols.push(std::mem::take(&mut current));
                } else {
                    current.clear();
                }
            } else if pending_spaces == 1 && !current.is_empty() {
                current.push(' ');
            }
            pending_spaces = 0;
            current.push(c);
        }
    }
    if !strip_ansi(&current).trim().is_empty() {
        cols.push(current);
    }
    cols
}

/// Counts `*` characters that aren't wrapped in iwctl's dim-gray escape
/// (`\x1b[1;90m` ... `\x1b[0m`) — the visual "filled" signal bars.
fn count_active_stars(raw: &str) -> u8 {
    let mut active = 0u8;
    let mut dimmed = false;
    let mut chars = raw.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\u{1b}' && chars.peek() == Some(&'[') {
            let mut seq = String::new();
            chars.next();
            for c2 in chars.by_ref() {
                seq.push(c2);
                if c2.is_ascii_alphabetic() {
                    break;
                }
            }
            if seq.starts_with("1;90") {
                dimmed = true;
            } else if seq.starts_with('0') {
                dimmed = false;
            }
        } else if c == '*' && !dimmed {
            active += 1;
        }
    }
    active
}

fn run_output(cmd: &str, args: &[&str]) -> String {
    Command::new(cmd)
        .args(args)
        .output()
        .map(|o| String::from_utf8_lossy(&o.stdout).to_string())
        .unwrap_or_default()
}

// ── Bluetooth ────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Default)]
pub struct BluetoothAdapter {
    pub present: bool,
    pub powered: bool,
    pub discoverable: bool,
    pub pairable: bool,
    pub discovering: bool,
}

pub fn get_bluetooth_adapter() -> BluetoothAdapter {
    let out = run_output("bluetoothctl", &["show"]);
    if out.trim().is_empty() {
        return BluetoothAdapter::default();
    }
    let field = |key: &str| -> bool {
        out.lines()
            .find(|l| l.trim_start().starts_with(key))
            .is_some_and(|l| l.contains("yes"))
    };
    BluetoothAdapter {
        present: true,
        powered: field("Powered:"),
        discoverable: field("Discoverable:"),
        pairable: field("Pairable:"),
        discovering: field("Discovering:"),
    }
}

pub fn set_bluetooth_power(on: bool) {
    let _ = Command::new("bluetoothctl").args(["power", if on { "on" } else { "off" }]).output();
}

pub fn set_bluetooth_discoverable(on: bool) {
    let _ = Command::new("bluetoothctl").args(["discoverable", if on { "on" } else { "off" }]).output();
}

pub fn set_bluetooth_pairable(on: bool) {
    let _ = Command::new("bluetoothctl").args(["pairable", if on { "on" } else { "off" }]).output();
}

/// Blocks for a few seconds while bluetoothctl scans — call from a
/// background task, not directly from the UI thread.
pub fn bluetooth_scan() {
    let _ = Command::new("bluetoothctl").args(["--timeout", "5", "scan", "on"]).output();
}

#[derive(Debug, Clone)]
pub struct BluetoothDevice {
    pub mac: String,
    pub name: String,
    pub paired: bool,
    pub connected: bool,
    pub trusted: bool,
}

pub fn get_bluetooth_devices() -> Vec<BluetoothDevice> {
    let list = run_output("bluetoothctl", &["devices"]);
    let mut devices = Vec::new();
    for line in list.lines() {
        let rest = match line.trim().strip_prefix("Device ") {
            Some(r) => r,
            None => continue,
        };
        let Some((mac, name)) = rest.split_once(' ') else { continue };
        let info = run_output("bluetoothctl", &["info", mac]);
        let flag = |key: &str| -> bool {
            info.lines().find(|l| l.trim_start().starts_with(key)).is_some_and(|l| l.contains("yes"))
        };
        devices.push(BluetoothDevice {
            mac: mac.to_string(),
            name: name.trim().to_string(),
            paired: flag("Paired:"),
            connected: flag("Connected:"),
            trusted: flag("Trusted:"),
        });
    }
    devices.sort_by(|a, b| b.connected.cmp(&a.connected).then(b.paired.cmp(&a.paired)));
    devices
}

pub fn bluetooth_connect(mac: &str) {
    let _ = Command::new("bluetoothctl").args(["connect", mac]).output();
}

pub fn bluetooth_disconnect(mac: &str) {
    let _ = Command::new("bluetoothctl").args(["disconnect", mac]).output();
}

/// Pairing can require an interactive PIN/confirmation, so this runs in a
/// spawned terminal instead of a headless subprocess — same reasoning as
/// the sudo-password flows elsewhere in this file.
pub fn bluetooth_pair(terminal: &str, mac: &str) {
    let term = if terminal.is_empty() { "alacritty" } else { terminal };
    let script = format!(
        "bluetoothctl pair {mac} && bluetoothctl trust {mac}; echo; read -rsn1 -p 'Press any key to close...'"
    );
    let _ = Command::new(term).arg("-e").arg("bash").arg("-c").arg(script).spawn();
}

pub fn bluetooth_remove(mac: &str) {
    let _ = Command::new("bluetoothctl").args(["remove", mac]).output();
}

// ── WiFi ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Default)]
pub struct WifiStatus {
    pub powered: bool,
    pub connected_ssid: Option<String>,
    pub ip: Option<String>,
}

#[derive(Debug, Clone, Copy, PartialEq)]
enum NetworkBackend {
    NetworkManager,
    Iwd,
    None,
}

/// This machine runs iwd, so that's the only backend actually exercised
/// against a real system. NetworkManager is by far the more common default
/// on most other distros (Ubuntu, Fedora, Debian, etc.), so it's supported
/// too — built carefully against `nmcli`'s documented terse (`-t`) output
/// format, but unverified against a live NetworkManager install.
fn detect_network_backend() -> NetworkBackend {
    // `nmcli general status` only succeeds if the NetworkManager daemon is
    // actually running, not just installed — prefer it when active since
    // it's the more common default.
    if Command::new("nmcli").args(["-t", "general", "status"]).output()
        .is_ok_and(|o| o.status.success())
    {
        return NetworkBackend::NetworkManager;
    }
    if Command::new("which").arg("iwctl").output().is_ok_and(|o| o.status.success()) {
        return NetworkBackend::Iwd;
    }
    NetworkBackend::None
}

/// Splits an nmcli `-t` (terse) line on unescaped `:` — nmcli backslash-
/// escapes literal `:` and `\` inside field values in this mode.
fn parse_nmcli_terse_line(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut current = String::new();
    let mut chars = line.chars().peekable();
    while let Some(c) = chars.next() {
        if c == '\\' {
            if let Some(next) = chars.next() {
                current.push(next);
                continue;
            }
        }
        if c == ':' {
            fields.push(std::mem::take(&mut current));
        } else {
            current.push(c);
        }
    }
    fields.push(current);
    fields
}

fn wifi_iface() -> Option<String> {
    let out = run_output("iwctl", &["device", "list"]);
    for line in strip_ansi(&out).lines() {
        let cols = split_table_columns(line);
        if cols.len() >= 4 && cols[0] != "Name" {
            return Some(cols[0].clone());
        }
    }
    None
}

fn wifi_iface_nm() -> Option<String> {
    let out = run_output("nmcli", &["-t", "-f", "DEVICE,TYPE", "device", "status"]);
    for line in out.lines() {
        let cols = parse_nmcli_terse_line(line);
        if cols.len() >= 2 && cols[1] == "wifi" {
            return Some(cols[0].clone());
        }
    }
    None
}

fn interface_ip(iface: &str) -> Option<String> {
    let addr = run_output("ip", &["-4", "-o", "addr", "show", iface]);
    addr.split_whitespace()
        .position(|w| w == "inet")
        .and_then(|i| addr.split_whitespace().nth(i + 1))
        .map(|s| s.split('/').next().unwrap_or(s).to_string())
}

pub fn get_wifi_status() -> WifiStatus {
    let rfkill = run_output("rfkill", &["list", "wifi"]);
    let powered = !rfkill.contains("Soft blocked: yes") && !rfkill.is_empty();

    match detect_network_backend() {
        NetworkBackend::NetworkManager => {
            let Some(iface) = wifi_iface_nm() else { return WifiStatus { powered, ..Default::default() } };
            let out = run_output("nmcli", &["-t", "-f", "DEVICE,STATE,CONNECTION", "device", "status"]);
            let connected_ssid = out.lines()
                .map(parse_nmcli_terse_line)
                .find(|cols| cols.len() >= 3 && cols[0] == iface && cols[1] == "connected")
                .map(|cols| cols[2].clone())
                .filter(|s| !s.is_empty());
            let ip = connected_ssid.as_ref().and_then(|_| interface_ip(&iface));
            WifiStatus { powered, connected_ssid, ip }
        }
        NetworkBackend::Iwd => {
            let Some(iface) = wifi_iface() else { return WifiStatus { powered, ..Default::default() } };
            let show = strip_ansi(&run_output("iwctl", &["station", &iface, "show"]));
            let connected_ssid = show.lines()
                .find(|l| l.trim_start().starts_with("Connected network"))
                .and_then(|l| l.splitn(2, "Connected network").nth(1))
                .map(|s| s.trim().to_string())
                .filter(|s| !s.is_empty());
            let ip = connected_ssid.as_ref().and_then(|_| interface_ip(&iface));
            WifiStatus { powered, connected_ssid, ip }
        }
        NetworkBackend::None => WifiStatus { powered, ..Default::default() },
    }
}

pub fn set_wifi_power(on: bool) {
    // rfkill is the actual radio switch either way — NetworkManager and
    // iwd both just react to it, so this needs no backend-specific path.
    let _ = Command::new("rfkill").args([if on { "unblock" } else { "block" }, "wifi"]).output();
}

/// Blocks for a couple seconds while the backend scans — call from a
/// background task, not directly from the UI thread.
pub fn wifi_scan() {
    match detect_network_backend() {
        NetworkBackend::NetworkManager => {
            let _ = Command::new("nmcli").args(["device", "wifi", "rescan"]).output();
        }
        NetworkBackend::Iwd => {
            if let Some(iface) = wifi_iface() {
                let _ = Command::new("iwctl").args(["station", &iface, "scan"]).output();
            }
        }
        NetworkBackend::None => {}
    }
}

#[derive(Debug, Clone)]
pub struct WifiNetwork {
    pub ssid: String,
    pub security: String,
    pub signal_bars: u8,
    pub known: bool,
}

pub fn get_wifi_networks() -> Vec<WifiNetwork> {
    match detect_network_backend() {
        NetworkBackend::NetworkManager => get_wifi_networks_nm(),
        NetworkBackend::Iwd => get_wifi_networks_iwd(),
        NetworkBackend::None => Vec::new(),
    }
}

fn get_wifi_networks_nm() -> Vec<WifiNetwork> {
    let known_out = run_output("nmcli", &["-t", "-f", "NAME", "connection", "show"]);
    let known: Vec<String> = known_out.lines().map(str::to_string).collect();

    let out = run_output("nmcli", &["-t", "-f", "SSID,SECURITY,SIGNAL", "device", "wifi", "list"]);
    let mut networks = Vec::new();
    for line in out.lines() {
        let cols = parse_nmcli_terse_line(line);
        if cols.len() < 3 {
            continue;
        }
        let ssid = cols[0].trim().to_string();
        if ssid.is_empty() {
            continue;
        }
        let security = cols[1].trim().to_string();
        let signal: u8 = cols[2].trim().parse().unwrap_or(0);
        let signal_bars = ((signal as f32 / 100.0) * 4.0).round().min(4.0) as u8;
        let known = known.iter().any(|k| k == &ssid);
        networks.push(WifiNetwork { ssid, security, signal_bars, known });
    }
    networks
}

fn get_wifi_networks_iwd() -> Vec<WifiNetwork> {
    let Some(iface) = wifi_iface() else { return Vec::new() };
    let known_out = strip_ansi(&run_output("iwctl", &["known-networks", "list"]));
    let known: Vec<String> = known_out.lines()
        .skip_while(|l| !l.contains("Last connected"))
        .skip(1)
        .filter_map(|l| split_table_columns(l).into_iter().next())
        .collect();

    let out = run_output("iwctl", &["station", &iface, "get-networks"]);
    let mut networks = Vec::new();
    for line in out.lines() {
        let cols = split_table_columns_raw(line);
        if cols.len() < 3 {
            continue;
        }
        let ssid = strip_ansi(&cols[0]).trim().to_string();
        let security = strip_ansi(&cols[1]).trim().to_string();
        if ssid.is_empty() || ssid == "Network name" {
            continue;
        }
        let signal_bars = count_active_stars(&cols[2]);
        let known = known.iter().any(|k| k == &ssid);
        networks.push(WifiNetwork { ssid, security, signal_bars, known });
    }
    networks
}

/// Connecting to a new (unknown) network needs an interactive passphrase
/// prompt, so this always runs in a spawned terminal — for already-known
/// networks both backends reconnect immediately without asking anything.
pub fn wifi_connect(terminal: &str, ssid: &str) {
    let term = if terminal.is_empty() { "alacritty" } else { terminal };
    let script = match detect_network_backend() {
        NetworkBackend::NetworkManager => {
            format!("nmcli --ask device wifi connect \"{ssid}\"; echo; read -rsn1 -p 'Press any key to close...'")
        }
        NetworkBackend::Iwd => {
            let Some(iface) = wifi_iface() else { return };
            format!("iwctl station {iface} connect \"{ssid}\"; echo; read -rsn1 -p 'Press any key to close...'")
        }
        NetworkBackend::None => return,
    };
    let _ = Command::new(term).arg("-e").arg("bash").arg("-c").arg(script).spawn();
}

pub fn wifi_disconnect() {
    match detect_network_backend() {
        NetworkBackend::NetworkManager => {
            if let Some(iface) = wifi_iface_nm() {
                let _ = Command::new("nmcli").args(["device", "disconnect", &iface]).output();
            }
        }
        NetworkBackend::Iwd => {
            if let Some(iface) = wifi_iface() {
                let _ = Command::new("iwctl").args(["station", &iface, "disconnect"]).output();
            }
        }
        NetworkBackend::None => {}
    }
}

pub fn wifi_forget(ssid: &str) {
    match detect_network_backend() {
        // NetworkManager names the saved connection profile after the SSID
        // for auto-created wifi connections, which covers the common case.
        NetworkBackend::NetworkManager => {
            let _ = Command::new("nmcli").args(["connection", "delete", ssid]).output();
        }
        NetworkBackend::Iwd => {
            let _ = Command::new("iwctl").args(["known-networks", ssid, "forget"]).output();
        }
        NetworkBackend::None => {}
    }
}

// ── Ethernet ─────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct EthernetInterface {
    pub name: String,
    pub up: bool,
    pub carrier: bool,
    pub ip: Option<String>,
}

pub fn get_ethernet_interfaces() -> Vec<EthernetInterface> {
    let out = run_output("ip", &["-o", "link", "show"]);
    let mut interfaces = Vec::new();
    for line in out.lines() {
        let Some((_, rest)) = line.split_once(": ") else { continue };
        let Some((name, flags_rest)) = rest.split_once(": ") else { continue };
        if name == "lo" || name.starts_with("veth") || name.starts_with("docker")
            || name.starts_with("br-") || name.starts_with("tailscale") || name.starts_with("wg")
        {
            continue;
        }
        // Wireless interfaces expose a "wireless" subdirectory in sysfs —
        // that's how we tell them apart from real ethernet (both report
        // link/ether).
        if std::path::Path::new(&format!("/sys/class/net/{name}/wireless")).exists() {
            continue;
        }
        let up = flags_rest.contains("UP");
        let carrier = flags_rest.contains("LOWER_UP");
        let addr = run_output("ip", &["-4", "-o", "addr", "show", name]);
        let ip = addr.split_whitespace()
            .position(|w| w == "inet")
            .and_then(|i| addr.split_whitespace().nth(i + 1))
            .map(|s| s.split('/').next().unwrap_or(s).to_string());
        interfaces.push(EthernetInterface { name: name.to_string(), up, carrier, ip });
    }
    interfaces
}

/// Bringing an interface up/down needs root, so this runs in a spawned
/// terminal asking for the sudo password — same pattern as System Services.
pub fn set_ethernet_up(terminal: &str, iface: &str, up: bool) {
    let term = if terminal.is_empty() { "alacritty" } else { terminal };
    let action = if up { "up" } else { "down" };
    let script = format!(
        "sudo ip link set {iface} {action}; echo; read -rsn1 -p 'Press any key to close...'"
    );
    let _ = Command::new(term).arg("-e").arg("bash").arg("-c").arg(script).spawn();
}

// ── Updates ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub struct UpdateItem {
    /// Name shown in the list.
    pub name: String,
    /// Argument passed to the update command (pkgname, or flatpak app id).
    pub id: String,
    /// Empty for flatpak — `remote-ls --updates` doesn't report a version delta.
    pub old_version: String,
    pub new_version: String,
}

#[derive(Debug, Clone, Default)]
pub struct UpdateStatus {
    pub pacman: Vec<UpdateItem>,
    pub aur: Vec<UpdateItem>,
    pub flatpak: Vec<UpdateItem>,
    /// None until the corresponding tool has been probed once.
    pub aur_available: bool,
    pub flatpak_available: bool,
}

/// Parses `name old -> new` lines shared by `checkupdates` and `yay -Qua`.
fn parse_version_bump_lines(text: &str) -> Vec<UpdateItem> {
    text.lines()
        .filter(|l| !l.trim().is_empty())
        .filter_map(|line| {
            let parts: Vec<&str> = line.split_whitespace().collect();
            if parts.len() < 4 {
                return None;
            }
            Some(UpdateItem {
                name: parts[0].to_string(),
                id: parts[0].to_string(),
                old_version: parts[1].to_string(),
                new_version: parts[3].to_string(),
            })
        })
        .collect()
}

/// `checkupdates` syncs a separate pacman DB copy and needs no root; it
/// exits 2 with empty output when there's nothing to do, which is not an
/// error for us.
pub fn get_pacman_updates() -> Vec<UpdateItem> {
    Command::new("checkupdates")
        .output()
        .map(|o| parse_version_bump_lines(&String::from_utf8_lossy(&o.stdout)))
        .unwrap_or_default()
}

pub fn get_aur_updates() -> Option<Vec<UpdateItem>> {
    if Command::new("which").arg("yay").output().is_ok_and(|o| o.status.success()) {
        Command::new("yay").arg("-Qua").output().ok().map(|o| parse_version_bump_lines(&String::from_utf8_lossy(&o.stdout)))
    } else {
        None
    }
}

/// `flatpak remote-ls --updates` columns: Name, Application ID, Version,
/// Branch, Installation — no old-version delta available from this command.
pub fn get_flatpak_updates() -> Option<Vec<UpdateItem>> {
    if !Command::new("which").arg("flatpak").output().is_ok_and(|o| o.status.success()) {
        return None;
    }
    Command::new("flatpak").args(["remote-ls", "--updates"]).output().ok().map(|o| {
        String::from_utf8_lossy(&o.stdout)
            .lines()
            .filter(|l| !l.trim().is_empty())
            .filter_map(|line| {
                let cols: Vec<&str> = line.split('\t').collect();
                if cols.len() < 3 {
                    return None;
                }
                Some(UpdateItem {
                    name: cols[0].to_string(),
                    id: cols[1].to_string(),
                    old_version: String::new(),
                    new_version: cols[2].to_string(),
                })
            })
            .collect()
    })
}

pub fn get_update_status() -> UpdateStatus {
    let aur = get_aur_updates();
    let flatpak = get_flatpak_updates();
    UpdateStatus {
        pacman: get_pacman_updates(),
        aur_available: aur.is_some(),
        flatpak_available: flatpak.is_some(),
        aur: aur.unwrap_or_default(),
        flatpak: flatpak.unwrap_or_default(),
    }
}

/// pacman/yay need root and are interactive (pacman prompts to confirm the
/// transaction), so — same pattern as System Services — this spawns the
/// user's terminal instead of running headless. `pkg` is `None` for a full
/// "update all", `Some(name)` to target just one package.
pub fn update_pacman(terminal: &str, pkg: Option<&str>) {
    let term = if terminal.is_empty() { "alacritty" } else { terminal };
    let script = match pkg {
        Some(p) => format!("sudo pacman -S {p}; echo; read -rsn1 -p 'Press any key to close...'"),
        None => "sudo pacman -Syu; echo; read -rsn1 -p 'Press any key to close...'".to_string(),
    };
    let _ = Command::new(term).arg("-e").arg("bash").arg("-c").arg(script).spawn();
}

pub fn update_aur(terminal: &str, pkg: Option<&str>) {
    let term = if terminal.is_empty() { "alacritty" } else { terminal };
    let script = match pkg {
        Some(p) => format!("yay -S {p}; echo; read -rsn1 -p 'Press any key to close...'"),
        None => "yay -Sua; echo; read -rsn1 -p 'Press any key to close...'".to_string(),
    };
    let _ = Command::new(term).arg("-e").arg("bash").arg("-c").arg(script).spawn();
}

pub fn update_flatpak(terminal: &str, id: Option<&str>) {
    let term = if terminal.is_empty() { "alacritty" } else { terminal };
    let script = match id {
        Some(i) => format!("flatpak update -y {i}; echo; read -rsn1 -p 'Press any key to close...'"),
        None => "flatpak update -y; echo; read -rsn1 -p 'Press any key to close...'".to_string(),
    };
    let _ = Command::new(term).arg("-e").arg("bash").arg("-c").arg(script).spawn();
}

// ── Brightness ───────────────────────────────────────────────────────────

/// True if a real screen backlight device exists (laptop panel/eDP). False
/// on desktops with external monitors — those have no /sys/class/backlight
/// entry and rely on the monitor's own OSD/DDC controls instead, so the
/// brightness feature stays wired but should show as unavailable there.
pub fn has_backlight() -> bool {
    std::fs::read_dir("/sys/class/backlight")
        .map(|mut d| d.next().is_some())
        .unwrap_or(false)
}

pub fn get_brightness_percent() -> Option<u32> {
    let cur: u32 = Command::new("brightnessctl")
        .args(["--class=backlight", "get"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8_lossy(&o.stdout).trim().parse().ok())?;
    let max: u32 = Command::new("brightnessctl")
        .args(["--class=backlight", "max"])
        .output()
        .ok()
        .and_then(|o| String::from_utf8_lossy(&o.stdout).trim().parse().ok())?;
    if max == 0 { return None; }
    Some(((cur as f64 / max as f64) * 100.0).round() as u32)
}

pub fn set_brightness_percent(pct: u32) {
    let _ = Command::new("brightnessctl")
        .args(["--class=backlight", "set", &format!("{pct}%")])
        .output();
}

// ── Wallpaper ────────────────────────────────────────────────────────────

/// Non-recursive scan of the usual wallpaper spots for pick_list options.
pub fn scan_wallpapers() -> Vec<String> {
    let dirs = [
        format!("{}/desktop backgrounds", home()),
        format!("{}/Pictures/Wallpapers", home()),
        "/usr/share/backgrounds/sway".to_string(),
        "/usr/share/backgrounds".to_string(),
    ];
    let exts = ["jpg", "jpeg", "png", "webp", "bmp"];
    let mut found: Vec<String> = Vec::new();
    for dir in dirs {
        let Ok(entries) = std::fs::read_dir(&dir) else { continue };
        for entry in entries.flatten() {
            let p = entry.path();
            let is_match = p
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| exts.contains(&e.to_lowercase().as_str()))
                .unwrap_or(false);
            if is_match {
                if let Some(s) = p.to_str() {
                    found.push(s.to_string());
                }
            }
        }
    }
    found.sort();
    found.dedup();
    found
}

/// Opens a native file picker and copies the chosen image into
/// `~/desktop backgrounds` so it shows up in `scan_wallpapers` from then on.
/// Blocking (GTK dialog) — call via spawn_blocking, same as other slow calls.
pub fn import_wallpaper() -> Option<String> {
    let dest_dir = format!("{}/desktop backgrounds", home());
    let picked = rfd::FileDialog::new()
        .add_filter("Images", &["jpg", "jpeg", "png", "webp", "bmp"])
        .set_directory(&dest_dir)
        .pick_file()?;

    let _ = std::fs::create_dir_all(&dest_dir);
    let file_name = picked.file_name()?.to_str()?.to_string();
    let dest = std::path::Path::new(&dest_dir).join(&file_name);
    if picked != dest {
        std::fs::copy(&picked, &dest).ok()?;
    }
    dest.to_str().map(|s| s.to_string())
}

/// Rewrites the sway config's `output * bg` line for either mode and applies
/// it live via swaymsg — same split as `update_sway_layout`/`reload`.
pub fn apply_wallpaper(config: &Config) {
    let new_line = if config.wallpaper_mode == "color" {
        format!("output * bg {} solid_color", config.wallpaper_color)
    } else if !config.wallpaper_path.is_empty() {
        let fit = if config.wallpaper_fit.is_empty() { "fill" } else { &config.wallpaper_fit };
        format!("output * bg \"{}\" {}", config.wallpaper_path, fit)
    } else {
        return;
    };

    let config_path = format!("{}/.config/sway/config", home());
    let Ok(content) = std::fs::read_to_string(&config_path) else { return };
    let mut lines: Vec<String> = content.lines().map(|l| l.to_string()).collect();
    let mut handled = false;
    for line in &mut lines {
        let t = line.trim_start();
        if t.starts_with("output") && t.contains(" bg ") {
            *line = new_line.clone();
            handled = true;
            break;
        }
    }
    if !handled {
        lines.push(new_line.clone());
    }
    let _ = std::fs::write(&config_path, lines.join("\n") + "\n");

    let _ = Command::new("swaymsg").arg(&new_line).output();
}

// ── Login screen (LightDM) ──────────────────────────────────────────────

/// Reads the wallpaper path out of `output * bg "<path>" fill` in the sway
/// config — that's the single source of truth for the current wallpaper,
/// there's no separate field for it in our own Config.
pub fn get_current_wallpaper() -> Option<String> {
    let config_path = format!("{}/.config/sway/config", home());
    let content = std::fs::read_to_string(config_path).ok()?;
    for line in content.lines() {
        let t = line.trim();
        if t.starts_with("output") && t.contains(" bg ") {
            let start = t.find('"')?;
            let rest = &t[start + 1..];
            let end = rest.find('"')?;
            return Some(rest[..end].to_string());
        }
    }
    None
}

/// LightDM's greeter runs as its own `lightdm` system user, which can't
/// read into our 700 home directory — so the wallpaper has to be copied
/// somewhere world-readable, and the greeter config (root-owned, under
/// /etc) has to be edited to point at it. Both need root, hence the same
/// spawned-terminal-with-sudo pattern as pacman/system-service updates.
pub fn sync_greeter_background(terminal: &str, wallpaper: &str) {
    let term = if terminal.is_empty() { "alacritty" } else { terminal };
    let ext = std::path::Path::new(wallpaper)
        .extension()
        .and_then(|e| e.to_str())
        .unwrap_or("jpg");
    let dest = format!("/usr/share/backgrounds/sway-control/greeter-bg.{ext}");
    let conf = "/etc/lightdm/lightdm-gtk-greeter.conf";
    let script = format!(
        "sudo mkdir -p /usr/share/backgrounds/sway-control && \
         sudo cp \"{wallpaper}\" {dest} && sudo chmod 644 {dest} && \
         if grep -q '^background=' {conf}; then \
             sudo sed -i -E 's|^background=.*|background={dest}|' {conf}; \
         elif grep -q '^#background=' {conf}; then \
             sudo sed -i -E 's|^#background=.*|background={dest}|' {conf}; \
         else \
             echo 'background={dest}' | sudo tee -a {conf} >/dev/null; \
         fi && \
         if grep -q '^user-background=' {conf}; then \
             sudo sed -i -E 's|^user-background=.*|user-background=false|' {conf}; \
         elif grep -q '^#user-background=' {conf}; then \
             sudo sed -i -E 's|^#user-background=.*|user-background=false|' {conf}; \
         else \
             echo 'user-background=false' | sudo tee -a {conf} >/dev/null; \
         fi; \
         echo; read -rsn1 -p 'Press any key to close...'"
    );
    let _ = Command::new(term).arg("-e").arg("bash").arg("-c").arg(script).spawn();
}

#[cfg(test)]
mod nmcli_parsing_tests {
    use super::*;

    #[test]
    fn parses_plain_fields() {
        assert_eq!(
            parse_nmcli_terse_line("yes:MySSID:80:WPA2"),
            vec!["yes", "MySSID", "80", "WPA2"],
        );
    }

    #[test]
    fn unescapes_colon_inside_a_field() {
        // nmcli backslash-escapes literal `:` in field values (e.g. an SSID
        // containing a colon) so it isn't mistaken for a column separator.
        assert_eq!(
            parse_nmcli_terse_line(r"yes:My\:SSID:80:WPA2"),
            vec!["yes", "My:SSID", "80", "WPA2"],
        );
    }

    #[test]
    fn unescapes_backslash_itself() {
        assert_eq!(
            parse_nmcli_terse_line(r"a\\b:c"),
            vec![r"a\b", "c"],
        );
    }

    #[test]
    fn handles_empty_trailing_field() {
        // An open network reports an empty SECURITY column.
        assert_eq!(
            parse_nmcli_terse_line("MySSID::80"),
            vec!["MySSID", "", "80"],
        );
    }
}
